version: "3.8"
services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=speed_agro
    volumes:
      - .mysql_data:/var/lib/mysql:rw

  db-manager:
    image: phpmyadmin/phpmyadmin
    expose:
      - 80
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db
